---
- name: ManageIQ virtual machine
  hosts: localhost
  vars:
    - ansible_connection: local
    - ovirt_api_endpoint: https://ovirt.example.com/ovirt-engine/api
    - ovirt_api_username: admin
    - ovirt_api_password: secret
    - miq_vm_name: miq
    - miq_vm_cpus: 4
    - miq_vm_memory: 8
    - miq_vm_ip_address: 192.168.122.2
    - miq_vm_netmask: 255.255.255.0
    - miq_vm_gateway: 192.168.122.1
    - miq_vm_dns_servers: 192.168.122.1
    - miq_vm_dns_domain: example.com

  tasks:
    - block:
      - name: Authenticate against oVirt API
        ovirt_auth:
          url: "{{ ovirt_api_endpoint }}"
          username: "{{ ovirt_api_username }}"
          password: "{{ ovirt_api_password }}"
          insecure: yes
        tags:
          - ovirt_debug

      - name: Create virtual machine
        ovirt_vms:
          auth: "{{ ovirt_auth }}"
          name: "fd-{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
          cluster: OVH
          template: rhel-7-server-ci
          cpu_sockets: "{{ miq_vm_cpus }}"
          memory: "{{ miq_vm_memory }}GiB"
          cloud_init:
            custom_script: |
              runcmd:
                - nmcli connection modify eth0 ipv4.method static ipv4.addresses {{ miq_vm_ip_address }}/{{ miq_vm_subnet_prefix }} ipv4.gateway {{ miq_vm_gateway }} ipv4.dns {{ miq_vm_dns_servers }} ipv4.dns-search {{ miq_vm_dns_domain }}
                - echo 'DNS2=10.32.96.1' >> /etc/sysconfig/network-scripts/ifcfg-eth0
                - ifdown eth0
                - ifup eth0
                - hostnamectl set-hostname {{ miq_vm_name }}.{{ miq_vm_dns_domain }}

      - name: Add database disk to virtual machine
        ovirt_disks:
          auth: "{{ ovirt_auth }}"
          name: "fd-{{ miq_vm_name }}.{{ miq_vm_dns_domain }}_Disk2"
          vm_name: "fd-{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
          size: 40GiB
          format: cow
          interface: virtio
          storage_domain: fas2552

      - name: Add host to in memory inventory
        add_host:
          name: "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
          groups: miq_instances
          ansible_ssh_host: "{{ miq_vm_ip_address }}"
          ansible_user: root
          ansible_ssh_pass: redhat

      always:
        - name: Always revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"

- name: Wait for instances to come up
  hosts: localhost
  gather_facts: no
  vars:
    - ansible_connection: local

  tasks:
    - name: Wait for virtual machine to be started
      wait_for:
        host: "{{ miq_vm_ip_address }}"
        port: 22

- name: ManageIQ prerequisites installation
  hosts: ManageIQ
  roles:
    - role: manageiq.base_os

- name: ManageIQ database installation
  hosts: ManageIQ:&database
  roles:
    - role: manageiq.postgresql

- name: ManageIQ worker installation
  hosts: ManageIQ:&worker,ManageIQ:&ui
  roles:
    - role: manageiq.worker


- name: ManageIQ UI specialisation
  hosts: ManageIQ:&ui
  roles:
    - role: manageiq.ui
