---
- name: ManageIQ prerequisites installation
  hosts: ManageIQ
  roles:
    - role: manageiq.base_os

- name: ManageIQ database installation
  hosts: ManageIQ:&database
  roles:
    - role: manageiq.postgresql

- name: ManageIQ worker installation
  hosts: ManageIQ:&worker
  roles:
    - role: manageiq.worker


- name: ManageIQ UI specialisation
  hosts: ManageIQ:&ui
  roles:
    - role: manageiq.ui
