---
- name: Get list of existing providers
  uri:
    url: "https://{{ inventory_hostname }}/api/providers/?filter[]=name={{ item.name | regex_replace(' ', '%20') }}"
    user: "{{ miq_app_username }}"
    password: "{{ miq_app_password }}"
    method: GET
    validate_certs: no
  delegate_to: localhost
  connection: local
  register: providers_json

- name: Add extra providers
  uri:
    url: https://{{ inventory_hostname }}/api/providers
    user: "{{ miq_app_username }}"
    password: "{{ miq_app_password }}"
    method: POST
    validate_certs: no
    body_format: json
    body: "{{ item }}"
  delegate_to: localhost
  connection: local
  when: providers_json.json.subcount == 0
