---
manageiq_postgresql_version: "9.5"
manageiq_postgresql_scl: "rh-postgresql95"
manageiq_ruby_version: "2.4"
manageiq_ruby_scl: "rh-ruby24"
manageiq_logs_vg_name: "vg_miq_logs"
manageiq_logs_lv_name: "lv_data"
manageiq_git_repos:
  - name: manageiq-ui-classic
    username: ManageIQ
    branch: master
    deps_command: npm install
  - name: miq_v2v_ui_plugin
    username: priley86
    branch: migration-poc
    deps_command: npm install
  - name: manageiq
    username: ManageIQ
    branch: master
    deps_command: "scl enable {{ manageiq_ruby_scl }} {{ manageiq_postgresql_scl }} 'bundle install --jobs 3'"
manageiq_disabled_plugins:
  - graphql
