---
- name: Set facts for better readability
  set_fact:
    ruby_scl: "rh-ruby{{ manageiq_ruby_version | regex_replace('\\.', '') }}"

- name: Install additionnal gems
  command: "scl enable {{ ruby_scl }} 'gem install foreman'"

- block:
    - name: Clone ManageIQ Clussic UI plugin repository
      git:
        repo: https://github.com/ManageIQ/manageiq-ui-classic.git
        dest: /home/miq/manageiq-ui-classic
        version: master
        force: true

    - name: Clone Patrick Riley's V2V UI plugin repository
      git:
        repo: https://github.com/priley86/miq_v2v_ui_plugin.git
        dest: /home/miq/miq_v2v_ui_plugin
        version: migration-poc
        force: true

    - name: Add development repos to ManageIQ
      copy:
        dest: /home/miq/manageiq/bundler.d/Gemfile.dev.rb
        owner: miq
        group: miq
        mode: 0644
        content: |
          override_gem 'manageiq-ui-classic', :path => File.expand_path('../../manageiq-ui-classic', __dir__)
          gem 'miq_v2v_ui', :path => File.expand_path('../../miq_v2v_ui_plugin', __dir__)

    - name: Setup ManageIQ
      command: npm install
      args:
        chdir: /home/miq/miq_v2v_ui_plugin

    - name: Start ManageIQ
      command: scl enable {{ ruby_scl }} 'bundle exec bin/rake evm:start'
      args:
        chdir: /home/miq/manageiq

  become: true
  become_user: miq

- name: Wait for ManageIQ service to be up
  wait_for:
    port: 3000
    delay: 10
    sleep: 10
    timeout: 300
